# Generated by Django 3.0.8 on 2020-07-10 05:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MelghatHamlets23Apr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326)),
                ('fid', models.IntegerField(blank=True, null=True)),
                ('srno', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('field_2', models.CharField(blank=True, max_length=254, null=True)),
                ('state', models.CharField(blank=True, max_length=254, null=True)),
                ('district', models.CharField(blank=True, max_length=254, null=True)),
                ('block', models.CharField(blank=True, max_length=254, null=True)),
                ('habitation', models.CharField(blank=True, max_length=254, null=True)),
                ('facility_n', models.CharField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=254, null=True)),
                ('file_uploa', models.CharField(blank=True, max_length=254, null=True)),
                ('facility_c', models.CharField(blank=True, max_length=254, null=True)),
                ('facility_s', models.CharField(blank=True, max_length=254, null=True)),
                ('lattitude', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'melghat_hamlets_23apr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=10, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=10, max_digits=10)),
                ('address', models.CharField(max_length=254)),
                ('city', models.CharField(max_length=254)),
                ('state', models.CharField(max_length=254)),
                ('pin', models.DecimalField(decimal_places=6, max_digits=6)),
                ('domain', models.CharField(choices=[('agro', 'Agro'), ('edu', 'Education'), ('med', 'Medical'), ('trans', 'Transport/Admin')], max_length=254)),
                ('date', models.DateField()),
            ],
        ),
    ]
